name: documentation
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  docs:
    name: Documentation Proxy

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Evaluate Changes and Dispatch Documentation Updates
        id: evaluate
        uses: ./.github/actions/documentation-proxy
        with:
          pat-token: ${{ secrets.PAT_TOKEN }}