name: documentation.flow

run-name: >-
  [${{ github.event.client_payload.job_key }}] Flow Documentation

on:
  repository_dispatch:
    types: [update-documentation-flow]
  workflow_dispatch:
    inputs:
      job_key:
        description: 'Job Key to process'
        required: true
        type: string
      modified_files:
        description: 'Modified Files (Comma-Separated List)'
        required: true
        type: string

jobs:
  update-documentation-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Initialise Documentation
        id: context
        uses: ./.github/actions/initialise-docs
        with:
          job-key: ${{ github.event.client_payload.job_key || inputs.job_key }}
          modified-files: ${{ github.event.client_payload.modified_files || inputs.modified_files }}
          pat-token: ${{ secrets.PAT_TOKEN }}

      - name: Generate Prompt for Flow Documentation
        id: gen-prompt
        uses: ./.github/actions/gen-prompt
        with:
          job-key: ${{ steps.context.outputs.job-key }}
          prompt: ${{ vars.PROMPT_FLOW }}

      - name: Generate Documentation and Create PR
        id: gen-and-pr
        uses: ./.github/actions/gen-docs-plus-pr
        with:
          job-key: ${{ steps.context.outputs.job-key }}
          prompt: ${{ steps.gen-prompt.outputs.prompt }}
          pat-token: ${{ secrets.PAT_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
