name: Flow Documentation

run-name: >-
  [${{ github.event.client_payload.job_key }}] Flow Documentation

on:
  repository_dispatch:
    types: [update-documentation-flow]
  workflow_dispatch:
    inputs:
      job_key:
        description: 'Job Key to process'
        required: true
        type: string
      modified_files:
        description: 'Modified Files (Comma-Separated List)'
        required: true
        type: string

jobs:
  update-documentation-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Update Flow Documentation
        run: |
          echo "Updating documentation for flow: ${{ github.event.client_payload.job_key || inputs.job_key }}"
          echo "Modified files: ${{ github.event.client_payload.modified_files || inputs.modified_files }}"